name: tests
on: push
jobs:
  c-cl-error:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: actions/checkout@main
      - run: make -j3 test-c test-cl test-error
  cpp-java:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 21
      - uses: actions/checkout@main
      - run: make -j3 test-cpp test-java
  cs:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: actions/setup-dotnet@main
      - uses: actions/checkout@main
      - run: make -j3 test-cs
  d:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - uses: actions/checkout@main
      - run: make -j3 test-d
  js-ts:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: actions/checkout@main
      - run: make -j3 test-js test-ts
  py-swift:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - run: pip install mypy
      - uses: pfusik/setup-swift@gpg-www
      - uses: actions/checkout@main
      - run: make -j3 test-py test-swift
  host-diff:
    runs-on: ubuntu-22.04
    steps:
      - uses: Totto16/setup-gcc@master
        with:
          version: 13
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 21
      - uses: actions/setup-node@main
      - uses: actions/checkout@main
      - run: make -j3 host-diff
      - run: make -j3 java/GenBase.java
      - run: make -j3 host-diff-java
      - run: make -j3 test-error FUT_HOST=cs
      - run: make -j3 test-error FUT_HOST=java
      - run: make -j3 test-error FUT_HOST=node
